# Generated by Django 3.2.5 on 2021-07-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
