# Generated by Django 3.2.5 on 2021-07-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_record_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngRec',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.record')),
                ('issue_category', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Запись в журнал инженеров',
                'verbose_name_plural': 'Записи в журнале инженеров',
            },
            bases=('journal.record',),
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
