# Generated by Django 3.2.5 on 2021-07-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20210709_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirRec',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.record')),
                ('issue_category', models.TextField(default='', verbose_name='проблемы с записью\\эфиром')),
            ],
            options={
                'verbose_name': 'Запись в журнал режиссеров',
                'verbose_name_plural': 'Записи в журнале режиссеров',
            },
            bases=('journal.record',),
        ),
    ]
